services:
  # postgres:
  #   image: postgres:14-alpine
  #   ports:
  #     - 5432:5432
  #   volumes:
  #     - ~/apps/postgres:/var/lib/postgresql/data
  #   environment:
  #     - POSTGRES_PASSWORD=secret
  #     - POSTGRES_USER=user
  #     - POSTGRES_DB=steamdeals

  test:
    build:
      context: .
      dockerfile: ./dockerfiles/test/tester.Dockerfile
    command: pytest ./tests/tests.py --cov=app
    volumes:
      - ./appdata:/appdata
    # depends_on:
    #   - postgres
