services:
  apps-scraper:
    build: ./
    command: python3 ./apps-scraper.py
    volumes:
      - ./appdata:/appdata

  tags-creator:
    build: ./
    command: python3 ./tags-creator.py
    volumes:
      - ./appdata:/appdata

  app-details-scraper:
    build: ./
    command: python3 ./app-details-scraper.py
    volumes:
      - ./appdata:/appdata
    depends_on:
      apps-scraper:
        condition: service_completed_successfully
      tags-creator:
        condition: service_completed_successfully

  uploader:
    build: ./
    command: python3 ./apps-details-prices-uploader.py
    volumes:
      - ./appdata:/appdata
    depends_on:
      apps-scraper:
        condition: service_completed_successfully
      app-details-scraper:
        condition: service_completed_successfully
      tags-creator:
        condition: service_completed_successfully
# TODO UPDATE and Add tags-creator and tags-uploader

# game-tag-creator:
#   build: ./
#   command: python3 ./game-tag-creator.py
#   volumes:
#     - ./appdata:/appdata
#   depends_on:
#     games-scraper:
#       condition: service_completed_successfully

# game-tag-uploader:
#   build: ./
#   command: python3 ./game-tag-uploader.py
#   volumes:
#     - ./appdata:/appdata
#   depends_on:
#     game-tag-creator:
#       condition: service_completed_successfully
