services:
  test1:
    build: ./
    command: python3 ./test.py
    volumes:
      - ./appdata:/appdata
  test2:
    depends_on:
      test1:
        condition: service_completed_successfully
    build: ./
    command: python3 ./test2.py
    volumes:
      - ./appdata:/appdata
